#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Cloudflare Pages and DNS for dictionary.poamslayer.com.
#
# Everything here is a step an agent cannot take: it happens in the Cloudflare
# dashboard, behind a login, against an account no script holds a token for.
# The wizard exists so the procedure is walked the same way every time instead
# of being reconstructed from memory.
#
# Re-running it is safe. Cloudflare treats every stage below as idempotent, and
# the wizard offers the values from a previous run as defaults.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO="poamslayer/cmmc-dictionary"
DOMAIN="dictionary.poamslayer.com"
ZONE="poamslayer.com"

banner "CMMC Dictionary: Cloudflare Pages and DNS"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: find the account and the zone"
say "Pages needs an account, and the custom domain needs the $ZONE zone to be"
say "on Cloudflare DNS. It already is, so this stage only confirms which"
say "account you are working in."
open_url "https://dash.cloudflare.com/"
step "Sign in."
step "If you have more than one account, pick the one that holds $ZONE."
step "Open the $ZONE zone and read the Account ID from the right-hand panel."
ask CF_ACCOUNT_ID "Paste the Account ID:"
write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Pages: connect the repository"
say "Cloudflare builds the site itself on every push, so there is no deploy"
say "token and no CI workflow to keep working."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/create/pages"
step "Choose Pages, then 'Connect to Git'."
step "Authorize Cloudflare for GitHub if you have not already."
step "Grant it access to the $REPO repository. Only that one is needed."
step "Select $REPO and click 'Begin setup'."
note "If the repository is missing from the list, use 'Add account' or edit the"
note "GitHub app's repository access, then reload the page."
pause "Done? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Pages: build settings"
say "These four values are the whole build. Set them exactly."
say ""
step "Project name:        cmmc-dictionary"
step "Production branch:   main"
step "Framework preset:    Astro"
step "Build command:       npm run build"
step "Output directory:    dist"
say ""
warn "Astro 7 needs Node 22.12 or newer, and the Pages default is older."
say "The repository carries a .nvmrc that pins it, and Cloudflare reads that"
say "file. If a build ever fails on the Node version, add an environment"
say "variable NODE_VERSION = 22.12.0 under Settings, Variables and Secrets."
say ""
step "Click 'Save and Deploy'."
ask PAGES_PROJECT "Confirm the project name you used:"
write_env PAGES_PROJECT "$PAGES_PROJECT"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Pages: watch the first build"
say "The first build takes a couple of minutes. Watch it finish before you"
say "attach the domain, because a failed build gives you a domain that serves"
say "nothing and a confusing place to start debugging."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/view/$PAGES_PROJECT"
step "Wait for the deployment to read 'Success'."
step "Open the *.pages.dev link and confirm you get the site, not a 404."
note "If the build failed, read the log. A Node version error is the likely"
note "cause and stage 3 says how to fix it."
ask PAGES_DEV_URL "Paste the *.pages.dev URL:"
write_env PAGES_DEV_URL "$PAGES_DEV_URL"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Pages: attach $DOMAIN"
say "Because $ZONE is already on Cloudflare DNS, Cloudflare writes the CNAME"
say "for you. You do not add a DNS record by hand."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/view/$PAGES_PROJECT/domains"
step "Click 'Set up a custom domain'."
step "Enter $DOMAIN and continue."
step "Review the CNAME it offers, then click 'Activate domain'."
step "Wait for the status to move from 'Initializing' to 'Active'."
note "The certificate is issued in that step. It usually takes under a minute"
note "and can take up to fifteen."
pause "Showing 'Active'? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify from outside Cloudflare"
say "The dashboard saying 'Active' and the internet agreeing are two different"
say "claims. This stage checks the second one."
say ""
say "  resolving $DOMAIN"
if command -v dig >/dev/null 2>&1; then
  dig +short "$DOMAIN" | sed 's/^/    /' || true
else
  note "dig not installed; skipping the DNS check"
fi
say ""
say "  fetching https://$DOMAIN"
if command -v curl >/dev/null 2>&1; then
  curl -sSI --max-time 20 "https://$DOMAIN" | head -n 1 | sed 's/^/    /' || \
    warn "no response yet; DNS or the certificate may still be propagating"
else
  note "curl not installed; open https://$DOMAIN in a browser instead"
fi
say ""
if confirm "Did https://$DOMAIN serve the site?"; then
  say "Done. Every push to main now rebuilds and redeploys it."
else
  SKIPPED+=("$DOMAIN is not serving yet. Re-run this stage in ten minutes. If it still fails, check the custom domain status on the Pages project.")
fi

finish
